# Generated by Django 4.0.3 on 2022-05-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forms',
        ),
    ]
